name: Push Docker Hub CI

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get project version from pom.xml
        id: get_version
        run: echo "::set-output name=version::$(grep -oPm1 "(?<=<version>).*?(?=</version>)" pom.xml)"
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: VERSION=${{ steps.get_version.outputs.version }}
          push: true
          tags: wilche/wilche-test-action:v${{ steps.get_version.outputs.version }}
